version: "3.8"

networks:
  cc_scotiabank_network:
    driver: bridge

services:
#  ms-college-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - cc_scotiabank_network
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/db_cc_college
#      - SPRING_R2DBC_USERNAME=postgres
#      - SPRING_R2DBC_PASSWORD=postgres

  postgres:
    image: postgres:16
    container_name: postgres_cc_college
    environment:
      - POSTGRES_DB=db_cc_college
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cc_scotiabank_network

volumes:
  postgres_data:
