version: "3.8"

networks:
  # Red interna para el gateway (siempre disponible)
  api_internal_network:
    driver: bridge
  # Red externa para conectar con otros microservicios (opcional)
  cc_scotiabank_network:
    external: true

services:
  ms-college-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - api_internal_network
      - cc_scotiabank_network
    depends_on:
      - postgres
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/db_cc_college
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - LOG_PATH=/app/logs
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:16
    container_name: postgres_cc_college
    environment:
      - POSTGRES_DB=db_cc_college
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_internal_network
      - cc_scotiabank_network

volumes:
  postgres_data:
